export const HEALTH_QUOTES: string[] = [
  "Take care of your body. It's the only place you have to live. — Jim Rohn",
  "A healthy outside starts from the inside. — Robert Urich",
  "The groundwork for all happiness is good health. — Leigh Hunt",
  "Movement is a medicine for creating change in a person's physical, emotional, and mental states.",
  "He who has health has hope; and he who has hope has everything. — Thomas Carlyle",
  "Your body hears everything your mind says. — Naomi Judd",
  "Sleep is the best meditation. — Dalai Lama",
  "Walking is the best possible exercise. — Thomas Jefferson",
  "An ounce of prevention is worth a pound of cure. — Benjamin Franklin",
  "To keep the body in good health is a duty… otherwise we shall not be able to keep our mind strong and clear. — Buddha",
  "Health is not valued till sickness comes. — Thomas Fuller",
  "Let food be thy medicine and medicine be thy food. — Hippocrates",
  "The first wealth is health. — Ralph Waldo Emerson",
  "Strength does not come from the body. It comes from the will.",
  "Small daily improvements are the key to staggering long-term results.",
  "Discipline is choosing between what you want now and what you want most.",
  "You don't have to be extreme, just consistent.",
  "Your future self is built by today's reps.",
  "Hydrate. Breathe. Move. Sleep. Repeat.",
  "The best project you'll ever work on is you.",
];